import Head from 'next/head'
import prisma from '../lib/prisma';
import { startOfToday, endOfToday } from 'date-fns'
import { postToEmailAPI } from '../utils/dateUtils';

import Layout from "../components/Layout"
import SendClientEmail from '../components/emails/SendEmail';

export default function SendEmail({ allBirthdays }) {

  return (
    <>
      <Head>
        <title>Birthday reminders App: Send Emails</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <SendClientEmail allBirthdays={allBirthdays} />
      </Layout>
    </>
  )

}

export const getServerSideProps = async () => {
  // All birthdays
  const allBirthdays = await prisma.bio.findMany({
    where: { published: true },
    include: {
      author: {
        select: {
          name: true,
          email: true
        },
      },
    },
  });

  return {
    props: {
      allBirthdays
    }
  }
}
