name: daily-cron-job
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: daily-cron-job
        run: |
          curl --request POST \
          --url 'https://prisma-birthdays.vercel.app/api/birthdays/birthday-email' \
          --header 'Authorization: Bearer ${{ secrets.BIRTHDAY_CRON }}'
